name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Ubuntu Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |
          cd /var/www/testflaskapp
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flaskapp
