name: Deploy Dev Flask

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Flask Dev
        run: |
          cd /var/www/flask/dev
          git fetch origin
          git reset --hard origin/dev
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-dev
