name: Deploy Flask (Self Hosted)

on:
  push:
    branches:
      - develop
      - uat
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: self-hosted

    steps:
      - name: Deploy Dev
        run: |
          cd /var/www/flask/dev
          git pull origin develop
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-dev

  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: self-hosted

    steps:
      - name: Deploy UAT
        run: |
          cd /var/www/flask/uat
          git pull origin uat
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-uat

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Deploy Prod
        run: |
          cd /var/www/flask/prod
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-prod
